export default [
  { color: "bg-rose-300" },
  { color: "bg-red-300" },
  { color: "bg-orange-300" },
  { color: "bg-amber-300" },
  { color: "bg-yellow-300" },
  { color: "bg-lime-300" },
  { color: "bg-green-300" },
  { color: "bg-emerald-300" },
  { color: "bg-teal-300" },
  { color: "bg-blue-300" },
  { color: "bg-sky-300" },
  { color: "bg-cyan-300" },
  { color: "bg-violet-300" },
  { color: "bg-purple-300" },
  { color: "bg-fuchsia-300" },
  { color: "bg-pink-300" },
  { color: "bg-black" },
  { color: "bg-gray-300" },
  { color: "bg-white-300" },
];
